apiVersion: spark.apache.org/v1
kind: SparkApplication
metadata:
  name: spark-pi-example
  namespace: spark-operator
spec:
  mainClass: "org.apache.spark.examples.SparkPi"
  jars: "local:///opt/spark/examples/jars/spark-examples.jar"
  
  # Spark configuration
  sparkConf:
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "apache/spark:4.0.0"
    spark.executor.instances: "2"
    spark.executor.cores: "2"
    spark.executor.memory: "2g"
    spark.driver.cores: "1"
    spark.driver.memory: "1g"
  
  # Runtime versions
  runtimeVersions:
    sparkVersion: "4.0.0"
  
  # Application tolerations
  applicationTolerations:
    resourceRetainPolicy: OnFailure
  
  # Driver specification with pod template
  driverSpec:
    podTemplateSpec:
      spec:
        containers:
          - name: spark-kubernetes-driver
            volumeMounts:
              - name: nvme-storage
                mountPath: /mnt/nvme
              - name: hdd-storage
                mountPath: /mnt/hdd
              - name: gcs-storage
                mountPath: /mnt/gcs
        volumes:
          - name: nvme-storage
            hostPath:
              path: /mnt/nvme
              type: Directory
          - name: hdd-storage
            hostPath:
              path: /mnt/hdd
              type: Directory
          - name: gcs-storage
            hostPath:
              path: /mnt/gcs
              type: Directory
  
  # Executor specification with pod template
  executorSpec:
    podTemplateSpec:
      spec:
        containers:
          - name: spark-kubernetes-executor
            volumeMounts:
              - name: nvme-storage
                mountPath: /mnt/nvme
              - name: hdd-storage
                mountPath: /mnt/hdd
              - name: gcs-storage
                mountPath: /mnt/gcs
        volumes:
          - name: nvme-storage
            hostPath:
              path: /mnt/nvme
              type: Directory
          - name: hdd-storage
            hostPath:
              path: /mnt/hdd
              type: Directory
          - name: gcs-storage
            hostPath:
              path: /mnt/gcs
              type: Directory
