apiVersion: spark.apache.org/v1
kind: SparkCluster
metadata:
  name: spark-cluster
  namespace: spark-operator
spec:
  # Runtime versions
  runtimeVersions:
    sparkVersion: "4.0.0"
  
  # Cluster tolerations - worker instance configuration
  clusterTolerations:
    instanceConfig:
      initWorkers: 3
      minWorkers: 1
      maxWorkers: 3
  
  # Spark configuration with HDFS and PostgreSQL connectivity
  sparkConf:
    spark.kubernetes.container.image: "apache/spark:4.0.0"
    spark.master.ui.title: "ResearchOps Spark Cluster"
    spark.master.rest.enabled: "true"
    spark.master.rest.host: "0.0.0.0"
    spark.ui.reverseProxy: "true"
    spark.executor.memory: "12g"
    spark.executor.cores: "4"
    spark.driver.memory: "4g"
    spark.driver.cores: "2"
    spark.local.dir: "/mnt/nvme/spark-tmp"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "hdfs://hdfs-cluster-namenode-default-0.hdfs-cluster-namenode-default:9000/spark-events"
    spark.history.fs.logDirectory: "hdfs://hdfs-cluster-namenode-default-0.hdfs-cluster-namenode-default:9000/spark-events"
    # HDFS Configuration
    spark.hadoop.fs.defaultFS: "hdfs://hdfs-cluster-namenode-default-0.hdfs-cluster-namenode-default:9000"
    spark.hadoop.dfs.client.use.datanode.hostname: "true"
    # PostgreSQL JDBC Configuration
    spark.jars.packages: "org.postgresql:postgresql:42.7.3"
    spark.sql.catalogImplementation: "in-memory"
  
  # Master specification with pod template
  masterSpec:
    statefulSetSpec:
      template:
        spec:
          containers:
            - name: master
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
              volumeMounts:
                - name: nvme-storage
                  mountPath: /mnt/nvme
                - name: hdd-storage
                  mountPath: /mnt/hdd
                - name: gcs-storage
                  mountPath: /mnt/gcs
          volumes:
            - name: nvme-storage
              hostPath:
                path: /mnt/nvme
                type: Directory
            - name: hdd-storage
              hostPath:
                path: /mnt/hdd
                type: Directory
            - name: gcs-storage
              hostPath:
                path: /mnt/gcs
                type: Directory
  
  # Worker specification with pod template
  workerSpec:
    statefulSetSpec:
      template:
        spec:
          containers:
            - name: worker
              resources:
                requests:
                  cpu: "2"
                  memory: "8Gi"
                limits:
                  cpu: "4"
                  memory: "16Gi"
              volumeMounts:
                - name: nvme-storage
                  mountPath: /mnt/nvme
                - name: hdd-storage
                  mountPath: /mnt/hdd
                - name: gcs-storage
                  mountPath: /mnt/gcs
          volumes:
            - name: nvme-storage
              hostPath:
                path: /mnt/nvme
                type: Directory
            - name: hdd-storage
              hostPath:
                path: /mnt/hdd
                type: Directory
            - name: gcs-storage
              hostPath:
                path: /mnt/gcs
                type: Directory
