apiVersion: spark.apache.org/v1
kind: SparkApplication
metadata:
  name: data-preprocessing-job
  namespace: spark-operator
spec:
  mainClass: "preprocessing.py"
  
  # Spark configuration
  sparkConf:
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "apache/spark-py:4.0.0"
    spark.executor.instances: "3"
    spark.executor.cores: "4"
    spark.executor.memory: "12g"
    spark.driver.cores: "2"
    spark.driver.memory: "4g"
    spark.local.dir: "/mnt/nvme/spark-tmp"
    spark.sql.warehouse.dir: "/mnt/nvme/spark-warehouse"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "/mnt/nvme/spark-events"
    # Optimize for single node with multiple executors
    spark.locality.wait: "3s"
    spark.scheduler.mode: "FAIR"
  
  # Runtime versions
  runtimeVersions:
    sparkVersion: "4.0.0"
  
  # Application tolerations
  applicationTolerations:
    resourceRetainPolicy: OnFailure
  
  # Driver specification with pod template
  driverSpec:
    podTemplateSpec:
      metadata:
        labels:
          app: data-preprocessing
          component: driver
          version: "4.0.0"
      spec:
        containers:
          - name: spark-kubernetes-driver
            volumeMounts:
              - name: nvme-storage
                mountPath: /mnt/nvme
              - name: hdd-storage
                mountPath: /mnt/hdd
              - name: gcs-storage
                mountPath: /mnt/gcs
        volumes:
          - name: nvme-storage
            hostPath:
              path: /mnt/nvme
              type: Directory
          - name: hdd-storage
            hostPath:
              path: /mnt/hdd
              type: Directory
          - name: gcs-storage
            hostPath:
              path: /mnt/gcs
              type: Directory
  
  # Executor specification with pod template
  executorSpec:
    podTemplateSpec:
      metadata:
        labels:
          app: data-preprocessing
          component: executor
          version: "4.0.0"
      spec:
        containers:
          - name: spark-kubernetes-executor
            volumeMounts:
              - name: nvme-storage
                mountPath: /mnt/nvme
              - name: hdd-storage
                mountPath: /mnt/hdd
              - name: gcs-storage
                mountPath: /mnt/gcs
        volumes:
          - name: nvme-storage
            hostPath:
              path: /mnt/nvme
              type: Directory
          - name: hdd-storage
            hostPath:
              path: /mnt/hdd
              type: Directory
          - name: gcs-storage
            hostPath:
              path: /mnt/gcs
              type: Directory
