---
# HDFS Cluster - 단일 노드 구성 with Storage Tiers
# Hot Data (NVME SSD 2TB): 최대 2일
# Cold Data (SATA HDD 2TB): 최소 2일 후
# Archive Data (GCS 1PB): 최소 1주일 후
# Checksum 기반 변경 감지 및 마이그레이션
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs-cluster
  namespace: default
spec:
  image:
    productVersion: "3.4.1"
  clusterConfig:
    zookeeperConfigMapName: hdfs-znode
    dfsReplication: 1  # 단일 노드 구성
    hdfsConfigOverrides:
      dfs.datanode.data.dir: "[SSD]file:///mnt/nvme/hdfs-data"  # Hot storage
      dfs.storage.policy.enabled: "true"
  nameNodes:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              min: "500m"
              max: "2000m"
            memory:
              limit: "4Gi"
        podOverrides:
          spec:
            nodeSelector:
              kubernetes.io/hostname: "hp-z440"
  dataNodes:
    roleGroups:
      hot:  # NVME SSD for Hot Data
        replicas: 1
        config:
          resources:
            cpu:
              min: "1000m"
              max: "4000m"
            memory:
              limit: "8Gi"
        podOverrides:
          spec:
            volumes:
              - name: nvme-storage
                hostPath:
                  path: /mnt/nvme/hdfs-data
                  type: DirectoryOrCreate
              - name: hdd-storage
                hostPath:
                  path: /mnt/hdd/hdfs-data
                  type: DirectoryOrCreate
              - name: gcs-storage
                hostPath:
                  path: /mnt/gcs/hdfs-data
                  type: DirectoryOrCreate
            containers:
              - name: datanode
                volumeMounts:
                  - name: nvme-storage
                    mountPath: /mnt/nvme/hdfs-data
                  - name: hdd-storage
                    mountPath: /mnt/hdd/hdfs-data
                  - name: gcs-storage
                    mountPath: /mnt/gcs/hdfs-data
            nodeSelector:
              kubernetes.io/hostname: "hp-z440"
  journalNodes:
    roleGroups:
      default:
        replicas: 1
        podOverrides:
          spec:
            nodeSelector:
              kubernetes.io/hostname: "hp-z440"
