#!/bin/bash
set -e

echo "================================================"
echo "Setting up Google OAuth for JupyterHub"
echo "================================================"
echo ""

echo "Follow these steps to configure Google OAuth:"
echo ""
echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
echo ""
echo "2. Create a new project or select existing project"
echo ""
echo "3. Enable Google+ API:"
echo "   - Navigate to 'APIs & Services' > 'Library'"
echo "   - Search for 'Google+ API'"
echo "   - Click 'Enable'"
echo ""
echo "4. Create OAuth 2.0 credentials:"
echo "   - Navigate to 'APIs & Services' > 'Credentials'"
echo "   - Click 'Create Credentials' > 'OAuth client ID'"
echo "   - Select 'Web application'"
echo "   - Add authorized redirect URIs:"
echo "     http://<your-jupyterhub-ip>:30080/hub/oauth_callback"
echo "     https://<your-jupyterhub-domain>/hub/oauth_callback"
echo ""
echo "5. Update values.yaml with your credentials:"
echo ""
echo "   GoogleOAuthenticator:"
echo "     client_id: \"YOUR_CLIENT_ID.apps.googleusercontent.com\""
echo "     client_secret: \"YOUR_CLIENT_SECRET\""
echo "     oauth_callback_url: \"http://<your-ip>:30080/hub/oauth_callback\""
echo "     hosted_domain:"
echo "       - \"your-domain.com\""
echo ""
echo "6. Apply the updated configuration:"
echo "   helm upgrade jupyterhub jupyterhub/jupyterhub \\"
echo "     --namespace jupyterhub \\"
echo "     --values values.yaml"
echo ""
echo "================================================"
echo ""
