# deployments/postgresql/cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db
  namespace: default
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: "nvme-storage"
    size: 500Gi

  superuserSecret:
    name: postgres-superuser-secret

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "2GB"

  monitoring:
    enablePodMonitor: true

