# deployments/hadoop/data-tiering-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hdfs-data-tiering
  namespace: default
spec:
  schedule: "0 2 * * *" # Run daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-tiering-manager
            # This image should contain kubectl, hdfs client, and rclone
            image: your-custom-data-tools-image:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              set -ex

              # --- Hot to Cold Data Tiering (NVMe -> HDD) ---
              # Logic to identify files older than 2 days in the 'hot' HDFS storage
              # and move them to the 'cold' storage.
              # This is a conceptual example. The actual HDFS commands might differ.
              echo "Starting Hot to Cold data tiering..."
              # hdfs dfs -moveFromLocal /path/on/nvme/older_than_2_days/* /path/on/hdd/

              # --- Cold to Archive Data Tiering (HDD -> GCP Storage) ---
              # Configure rclone with GCP credentials from a secret
              echo "Configuring rclone for GCP..."
              # This secret needs to be created with your rclone.conf or GCP service account key
              # kubectl create secret generic gcp-creds --from-file=rclone.conf=/path/to/rclone.conf
              mkdir -p /root/.config/rclone
              ln -s /etc/gcp/rclone.conf /root/.config/rclone/rclone.conf

              echo "Starting Cold to Archive data tiering..."
              # Logic to identify files older than 7 days in 'cold' HDFS storage
              # and move them to GCP Storage using rclone.
              # The checksum option (--checksum) can be used to avoid re-uploading identical files.
              # rclone move --checksum /path/on/hdd/older_than_7_days/ gcp:your-archive-bucket/

              echo "Data tiering job finished."
            volumeMounts:
            - name: gcp-creds
              mountPath: "/etc/gcp"
              readOnly: true
          volumes:
          - name: gcp-creds
            secret:
              secretName: gcp-creds # Secret containing rclone config or GCP service account key
          restartPolicy: OnFailure
