# deployments/hadoop/hdfs-cluster.yaml
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs-cluster
  namespace: default
spec:
  clusterConfig:
    dfs:
      replication: 3
  nameNodes:
    roleGroups:
      default:
        replicas: 2
        config:
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
        storage:
          data:
            capacity: "50Gi"
            storageClass: "local-path"
  dataNodes:
    roleGroups:
      hot: # NVMe Storage
        replicas: 3
        config:
          resources:
            requests:
              cpu: "1"
              memory: "8Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
        storage:
          data:
            - capacity: "1500Gi" # Approx 1.5TB for hot data
              storageClass: "nvme-storage" # This needs to be created
      cold: # HDD Storage
        replicas: 3
        config:
          resources:
            requests:
              cpu: "500m"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
        storage:
          data:
            - capacity: "1800Gi" # Approx 1.8TB for cold data
              storageClass: "hdd-storage" # This needs to be created
