---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "grafana"
    datasources: "grafana"
spec:
  config:
    log:
      mode: "console"
      level: "info"
    server:
      root_url: "https://grafana.mireu.xyz"
    security:
      admin_user: admin
      admin_password: admin123
    auth:
      disable_login_form: "false"
    auth.generic_oauth:
      enabled: "true"
      name: "Keycloak"
      allow_sign_up: "true"
      client_id: "grafana"
      client_secret: "REPLACE_WITH_GRAFANA_CLIENT_SECRET"
      scopes: "openid profile email"
      auth_url: "https://keycloak.mireu.xyz/realms/researchope/protocol/openid-connect/auth"
      token_url: "https://keycloak.mireu.xyz/realms/researchope/protocol/openid-connect/token"
      api_url: "https://keycloak.mireu.xyz/realms/researchope/protocol/openid-connect/userinfo"
      role_attribute_path: "contains(groups[*], 'master-admin') && 'Admin' || 'Viewer'"
      allow_assign_grafana_admin: "true"
    users:
      allow_sign_up: "true"
      auto_assign_org: "true"
      auto_assign_org_role: "Viewer"
  deployment:
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:latest
              resources:
                requests:
                  cpu: "500m"
                  memory: "512Mi"
                limits:
                  cpu: "2000m"
                  memory: "2Gi"
  service:
    spec:
      type: NodePort
      ports:
        - name: http
          port: 3000
          targetPort: 3000
          nodePort: 30300
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-path
