---
# Prometheus DataSource for Kubernetes metrics
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-server.monitoring:9090
    isDefault: true
    jsonData:
      timeInterval: "30s"
      httpMethod: "POST"
    editable: true
---
# PostgreSQL DataSource for ResearchOps database
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: postgres-datasource
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres-cluster-rw.default.svc.cluster.local:5432
    database: researchops
    user: researchops
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: "changeme"
    editable: true
---
# Loki DataSource for logs (if available)
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-datasource
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Loki
    type: loki
    access: proxy
    url: http://loki.monitoring:3100
    jsonData:
      maxLines: 1000
    editable: true
