# 01-k3s-core/01-storage-class.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: kube-system
data:
  config.json: |
    {
        "nodePathMap":[
        {
            "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths":[
                "/mnt/nvme/k3s-data",
                "/mnt/hdd/k3s-data"
            ]
        }
        ]
    }

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-hot-storage
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: "/mnt/nvme/k3s-data"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-cold-storage
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: "/mnt/hdd/k3s-data"