---
# Google OAuth Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: google-client-secret
  namespace: keycloak
type: Opaque
stringData:
  clientId: ""
  clientSecret: ""
---
# Keycloak Realm Import
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: researchope-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    id: researchope
    realm: researchope
    displayName: "ResearchOpe Platform"
    enabled: true
    sslRequired: external
    registrationAllowed: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    bruteForceProtected: true
    
    # Roles
    roles:
      realm:
        - name: master-admin
          description: "Master administrator role for JupyterHub and Grafana"
        - name: data-engineer
          description: "Data engineer role with access to Spark, HDFS, PostgreSQL"
        - name: researcher
          description: "Researcher role with limited access"
    
    # Google OAuth Identity Provider will be configured via API
    # due to secret reference limitations
    
    # Token settings
    accessTokenLifespan: 3600
    accessTokenLifespanForImplicitFlow: 900
    ssoSessionIdleTimeout: 1800
    ssoSessionMaxLifespan: 36000
    offlineSessionIdleTimeout: 2592000
    
    # Additional security settings
    attributes:
      frontendUrl: "https://keycloak.mireu.xyz"
