---
# JupyterHub Client Configuration (Master Admin - Google OAuth)
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: jupyterhub-client
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: researchope
    clients:
      - clientId: jupyterhub
        name: "JupyterHub"
        description: "JupyterHub - Research Environment (Master Admin Access)"
        enabled: true
        publicClient: false
        protocol: openid-connect
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: false
        redirectUris:
          - "https://jupyter.mireu.xyz/*"
          - "https://jupyter.mireu.xyz/hub/oauth_callback"
        webOrigins:
          - "https://jupyter.mireu.xyz"
        defaultRoles:
          - master-admin
        attributes:
          "oauth2.device.authorization.grant.enabled": "false"
          "oidc.ciba.grant.enabled": "false"
---
# Grafana Client Configuration (Master Admin - Google OAuth)
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: grafana-client
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: researchope
    clients:
      - clientId: grafana
        name: "Grafana"
        description: "Grafana - Monitoring Dashboard (Master Admin Access)"
        enabled: true
        publicClient: false
        protocol: openid-connect
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: false
        redirectUris:
          - "https://grafana.mireu.xyz/*"
          - "https://grafana.mireu.xyz/login/generic_oauth"
        webOrigins:
          - "https://grafana.mireu.xyz"
        defaultRoles:
          - master-admin
        attributes:
          "oauth2.device.authorization.grant.enabled": "false"
          "oidc.ciba.grant.enabled": "false"
---
# Spark Client Configuration (Token-based access)
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: spark-client
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: researchope
    clients:
      - clientId: spark
        name: "Apache Spark"
        description: "Apache Spark - Data Processing (Token Access)"
        enabled: true
        publicClient: false
        protocol: openid-connect
        standardFlowEnabled: false
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
        redirectUris:
          - "https://spark.mireu.xyz/*"
        webOrigins:
          - "https://spark.mireu.xyz"
        defaultRoles:
          - data-engineer
        attributes:
          "oauth2.device.authorization.grant.enabled": "false"
          "oidc.ciba.grant.enabled": "false"
          "client_credentials.use_refresh_token": "false"
---
# HDFS Client Configuration (Token-based access)
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: hdfs-client
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: researchope
    clients:
      - clientId: hdfs
        name: "HDFS"
        description: "Hadoop HDFS - Distributed Storage (Token Access)"
        enabled: true
        publicClient: false
        protocol: openid-connect
        standardFlowEnabled: false
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
        redirectUris:
          - "https://hdfs.mireu.xyz/*"
        webOrigins:
          - "https://hdfs.mireu.xyz"
        defaultRoles:
          - data-engineer
        attributes:
          "oauth2.device.authorization.grant.enabled": "false"
          "oidc.ciba.grant.enabled": "false"
          "client_credentials.use_refresh_token": "false"
---
# PostgreSQL Client Configuration (Token-based access)
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: postgres-client
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: researchope
    clients:
      - clientId: postgres
        name: "PostgreSQL"
        description: "PostgreSQL Database (Token Access)"
        enabled: true
        publicClient: false
        protocol: openid-connect
        standardFlowEnabled: false
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
        redirectUris:
          - "https://pgadmin.mireu.xyz/*"
        webOrigins:
          - "https://pgadmin.mireu.xyz"
        defaultRoles:
          - data-engineer
        attributes:
          "oauth2.device.authorization.grant.enabled": "false"
          "oidc.ciba.grant.enabled": "false"
          "client_credentials.use_refresh_token": "false"
