---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k3s-upgrade
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3s-upgrade
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k3s-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k3s-upgrade
subjects:
  - kind: ServiceAccount
    name: k3s-upgrade
    namespace: kube-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k3s-upgrade
  namespace: kube-system
spec:
  schedule: "0 3 * * 0"  # 매주 일요일 오전 3시
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k3s-upgrade
          hostNetwork: true
          hostPID: true
          restartPolicy: OnFailure
          containers:
          - name: k3s-upgrade
            image: rancher/k3s-upgrade:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "k3s 업그레이드 시작..."
              
              # 현재 k3s 버전 확인
              CURRENT_VERSION=$(k3s --version | head -n1 | awk '{print $3}')
              echo "현재 버전: $CURRENT_VERSION"
              
              # 최신 stable 버전 확인
              LATEST_VERSION=$(curl -s https://update.k3s.io/v1-release/channels/stable | jq -r '.data.latest')
              echo "최신 버전: $LATEST_VERSION"
              
              if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
                echo "업그레이드 진행 중... $CURRENT_VERSION -> $LATEST_VERSION"
                
                # k3s 업그레이드
                curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$LATEST_VERSION sh -
                
                # k3s 서비스 재시작
                systemctl restart k3s
                
                echo "k3s 업그레이드 완료!"
              else
                echo "최신 버전이 이미 설치되어 있습니다."
              fi
            securityContext:
              privileged: true
            volumeMounts:
            - name: host-root
              mountPath: /host
          volumes:
          - name: host-root
            hostPath:
              path: /
              type: Directory
