# deployments/prerequisites/letsencrypt-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "limmireu1214@gmail.com" # IMPORTANT: Replace with your email address
    privateKeySecretRef:
      name: letsencrypt-production-private-key
    solvers:
    - dns01:
        cloudflare:
          # Expects a secret named 'cloudflare-api-token-secret' in the cert-manager namespace
          # containing key 'api-token' with a Cloudflare API Token that has DNS edit permissions
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
