---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-import
  namespace: keycloak
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: realm-import
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for Keycloak to be ready..."
          until curl -s -f http://keycloak:8080/health/ready; do
            echo "Keycloak is not ready yet. Waiting..."
            sleep 10
          done
          
          echo "Keycloak is ready. Starting realm import..."
          
          # Get admin access token
          ACCESS_TOKEN=$(curl -s -X POST "http://keycloak:8080/realms/master/protocol/openid-connect/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=admin" \
            -d "password=ChangeMe123!" \
            -d "grant_type=password" \
            -d "client_id=admin-cli" | grep -o '"access_token":"[^"]*' | cut -d'"' -f4)
          
          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to get access token"
            exit 1
          fi
          
          echo "Successfully obtained access token"
          
          # Import realm configuration
          curl -v -X POST "http://keycloak:8080/admin/realms" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d @/config/researchops-realm.json
          
          echo "Realm import completed"
        volumeMounts:
        - name: realm-config
          mountPath: /config
      volumes:
      - name: realm-config
        configMap:
          name: keycloak-realm-config
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-clients-secrets
  namespace: keycloak
type: Opaque
stringData:
  google-client-id: "YOUR_GOOGLE_CLIENT_ID"
  google-client-secret: "YOUR_GOOGLE_CLIENT_SECRET"
  jupyterhub-client-secret: "jupyterhub-secret-change-me"
  grafana-client-secret: "grafana-secret-change-me"
  spark-client-secret: "spark-secret-change-me"
  hdfs-client-secret: "hdfs-secret-change-me"
  postgresql-client-secret: "postgresql-secret-change-me"
