# 03-automation/01-data-mover-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hot-to-cold-data-mover
  namespace: kube-system # 또는 관리용 네임스페이스
spec:
  schedule: "0 2 * * 0" # 매주 일요일 새벽 2시에 실행
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: data-mover
            image: alpine:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              echo "--- Starting data migration from NVMe to HDD ---"
              HOT_DATA_PATH="/mnt/nvme-data"
              COLD_DATA_PATH="/mnt/hdd-data"

              # 일주일 이상 수정되지 않은 파일을 찾아 HDD로 이동
              # -mtime +7 : 7일 이상 수정되지 않은 파일
              # -exec mv {} $COLD_DATA_PATH/ \; : 찾은 파일을 이동
              # 실제 프로덕션 환경에서는 rsync 등을 사용하여 더 안전하게 이동하는 것을 권장합니다.
              find $HOT_DATA_PATH -type f -mtime +7 -exec echo "Moving {} to $COLD_DATA_PATH/" \; -exec mv {} $COLD_DATA_PATH/ \;

              echo "--- Data migration finished ---"
            volumeMounts:
            - name: nvme-storage-mount
              mountPath: /mnt/nvme-data
            - name: hdd-storage-mount
              mountPath: /mnt/hdd-data
          volumes:
          # CronJob 포드가 노드의 실제 경로에 접근할 수 있도록 HostPath 사용
          - name: nvme-storage-mount
            hostPath:
              path: /mnt/nvme
              type: Directory
          - name: hdd-storage-mount
            hostPath:
              path: /mnt/hdd
              type: Directory